version: '3.9'
services:
  users:
    image: users:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - users-db
  search:
    image: search:0.0.1-SNAPSHOT
    ports:
      - "8081:8080"
    depends_on:
      elastic:
        condition: service_healthy
      redpanda:
        condition: service_healthy
  users-db:
    image: debezium/postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
  redpanda:
    image: vectorized/redpanda:v22.3.11
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
      - --check=false
    depends_on:
      - users-db
    healthcheck: { test: curl -f localhost:9644/v1/status/ready, interval: 1s, start_period: 10s }
  connect:
    image: debezium/connect:2.1.2.Final
    depends_on:
      - redpanda
      - users-db
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "redpanda:29092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "users.configs"
      OFFSET_STORAGE_TOPIC: "users.offset"
      STATUS_STORAGE_TOPIC: "users.status"
  elastic:
    image: elasticsearch:8.6.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
    healthcheck: { test: curl -f localhost:9200/_cat/indices, interval: 1s, start_period: 30s }
