object Constants {
    const val kotlinVersion = "1.7.22"
    const val springVersion = "3.0.2"
    const val springCloudVersion = "2022.0.1"
    const val mapstructVersion = "1.5.3.Final"
    const val testcontainersVersion = "1.17.6"
    const val coroutinesVersion = "1.6.4"
    const val dependencyManagementVersion = "1.1.0"
    const val jibVersion = "3.3.1"
    const val ktlintVersion = "11.2.0"
    const val datafakerVersion = "1.7.0"
    const val awaitilityVersion = "4.2.0"
    const val restAssuredVersion = "5.3.0"
    const val kotlinLoggingJvmVersion = "4.0.0-beta-11"
}
