server:
  port: 8080

spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: elastic:9200
  cloud:
    function:
      definition: userChangesConsumer
    stream:
      kafka:
        binder:
          brokers: redpanda:9092
      binders:
        users-changes-binder:
          type: kafka
      bindings:
        userChangesConsumer-in-0:
          binder: users-changes-binder
          destination: users.public.users
