server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: userChangesConsumer
    stream:
      binders:
        users-changes-binder:
          type: kafka
      bindings:
        userChangesConsumer-in-0:
          binder: users-changes-binder
          destination: dbserver1.public.users
